#!/bin/bash

FILENAME=$1
IP_ADDRESS=10.1.192.38

# shellcheck disable=SC2002
cat "$FILENAME" | grep $IP_ADDRESS | awk ' { match($0, /.+sid=\/(.+)\/&/, sid);}
		      { if (sid[1] != "") print sid[1];}' | sort
